// server/nosok-react/src/App.js
import React, { useEffect, useState } from 'react'
import Sidebar from './components/Sidebar/Sidebar'
import Header from './components/Header/Header'
import Content from './components/Content'
import { io } from 'socket.io-client'
import classes from './App.module.css'


async function fetchAPI(href) {
  if (href === '') return ''
  let response = await fetch('/api' + href)
                       .then(res => res.json())
                       .catch(e => {return ''})
  
  return response['content']
}

const socket = io('')
var href = '/log'

export default function App() {
  const [content, setContent] = useState('')

  const updContent = (ctn) => {
    switch (href) {
      case '/vars':
        setContent(JSON.stringify(ctn, null, 4))
        break;

      case '/log':
        setContent(ctn)
        break;

      default:
        break;
    }
  }
  
  useEffect(() => {
    let onDataChange = (payload) => {if (payload.href === href) updContent(payload.content)}

    fetchAPI(href).then(updContent)
    socket.on('data_changed', onDataChange)
    
    return () => {
      socket.off('data_changed', onDataChange)
    }
  }, [])

  return (
    <div className={classes.App}>
      <Header/>
      <Sidebar callback={(newHref) => {href = newHref; fetchAPI(newHref).then(updContent)}}/>
      <Content>{content}</Content>
    </div>
  )
}

// web_platform/nosok-solid/src/App.jsx
import { createSignal, onCleanup, onMount } from 'solid-js'

import Sidebar from './components/Sidebar/Sidebar'
import Header from './components/Header/Header'
import Content from './components/Content'
import { io } from 'socket.io-client'
import classes from './App.module.css'


async function fetchAPI(href) {
  if (href === '') return ''  // just in case

  return await fetch('/api' + href)
               .then(res => res.json())
               .then(data => data.content)
               .catch(_ => {return ''})
}

function prepareContent(ctn) {
  switch (href) {
    case '/vars':
      return JSON.stringify(ctn, null, 4)

    case '/log':
      return ctn

    default:
      return '';
  }
}

const socket = io('')
var href = '/log'

export default function App() {
  const [content, setContent] = createSignal('')
  const onDataChange = (payload) => {if (payload.href === href) setContent(prepareContent(payload.content))}
  
  onMount(() => {
    fetchAPI(href).then(prepareContent).then(setContent)

    socket.on(
      'data_changed', 
      onDataChange
    )
  })

  onCleanup(() => {
    socket.off(
      'data_changed',
      onDataChange
    )
    socket.disconnect()
  })

  return (
    <div className={classes.App}>
      <Header/>
      <Sidebar callback={(newHref) => {href = newHref; fetchAPI(newHref).then(prepareContent).then(setContent)}}/>
      <Content>{content}</Content>
    </div>
  )
}
